### ISSUE TITLE
TODO List of Basic Features

### ISSUE THREAD

**Issue by pratikmallya** [pratikmallya/schedule-docker-tasks#1]
- [x] Cli to talk to the api
- [x] Manage dependencies with godep
- [x] Deployment file to deploy the system on k8s
- [ ] Unit tests for main server path
- [x] Test if jobs are actually scheduled and run
- [x] Validation for crontab when creating tasks in both cli and api
- [x] Travis pipeline to push images to docker hub
- [ ] Use some kind of config file for configurable default values
- [ ] Capture output of scheduled docker commands
- [ ] Add endpoint to fetch those logs
- [ ] Persistent storage and recovery of schedules
- [ ] Partition tasks by user so users don't stomp on each others tasks (Access Control)
- [ ] Add explicit timeout to the task to prevent it from hogging resources
- [ ] Metrics, dashboards etc. to monitor the health, state of service
